import { DEFAULT_AVATAR, DEFAULT_USER_AVATAR } from '@/ProChat/const/meta';
import { ModelConfig } from '@/ProChat/types/config';
import { MetaData } from '@/ProChat/types/meta';
import { ChatMessage } from '@/types/message';
import { AutoCompleteProps } from 'antd';
import { TextAreaProps } from 'antd/es/input';
import { ReactNode } from 'react';
import { FlexBasicProps } from 'react-layout-kit/lib/FlexBasic';
import { Locale } from '../../locale';
import { ProChatChatReference } from '../ProChat';
